FROM registry.svc.ci.openshift.org/openshift/release:golang-1.11 AS builder
WORKDIR /go/src/github.com/kubernetes-csi/cluster-driver-registrar
COPY . .
RUN go build ./cmd/cluster-driver-registrar

FROM registry.svc.ci.openshift.org/openshift/origin-v4.0:base
COPY --from=builder /go/src/github.com/kubernetes-csi/cluster-driver-registrar/cluster-driver-registrar /usr/bin/
RUN useradd cluster-driver-registrar
USER cluster-driver-registrar
ENTRYPOINT ["/usr/bin/cluster-driver-registrar"]
